### ISSUE TITLE
ERROR:binance.websocket.binance_client_factory

### ISSUE THREAD

**Issue by escomputers** [escomputers/BASD#45]
### Discussed in https://github.com/escomputers/BASD/discussions/44

<div type='discussions-op-text'>

<sup>Originally posted by **andre9966** November 16, 2022</sup>
I run main from last alpha release, i set correctly configuration parameters but I have this error
ERROR:binance.websocket.binance_client_factory:Lost connection to Server. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
I have installed in my pc Python 3.11
</div>

**Comment by escomputers** [comment]
You don't need to install Python on your pc, .exe file has its own Python environment.

What operative system did you run BASD on? Please press the Windows logo key + R, type winver in the open box, and then select OK. Take a screenshot of window that will appear and attach it to this discussion.

When did you get that error? Soon after you click on "Validate" button?

**Comment by andre9966** [comment]
This is my Windows Version:
![winver](https://user-images.githubusercontent.com/118386454/202301563-8d3ddc23-7f3f-4cfa-8818-c4dd34863a82.PNG)

When I press "Validate", output windows appears with empty Textarea, when I click "Start" I see some DEBUG and INFO log but no ERRORS:

DEBUG:binance.api:url: https://api.binance.com/api/v3/userDataStream
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.binance.com:443
DEBUG:urllib3.connectionpool:https://api.binance.com:443 "POST /api/v3/userDataStream HTTP/1.1" 200 76
DEBUG:binance.api:raw response from server:{"listenKey":"***listenKey***"}
INFO:root:Receving listen key : ***listenKey***
INFO:binance.websocket.binance_socket_manager:Connection with URL: wss://stream.binance.com:9443/ws

I tried to buy on binance but oco request was not sent, I tried to click "Start" again but I got these errors:

WARNING:binance.websocket.binance_client_protocol:WebSocket connection closed: connection was closed uncleanly ("peer dropped the TCP connection without previous WebSocket closing handshake"), code: 1006, clean: False, reason: connection was closed uncleanly ("peer dropped the TCP connection without previous WebSocket closing handshake")
ERROR:binance.websocket.binance_client_factory:Lost connection to Server. Reason: [Failure instance: Traceback: <class 'NameError'>: name 'flot' is not defined
twisted\python\log.py:80:callWithContext
twisted\python\context.py:117:callWithContext
twisted\python\context.py:82:callWithContext
twisted\internet\selectreactor.py:153:_doReadOrWrite
--- <exception caught here> ---
twisted\internet\selectreactor.py:148:_doReadOrWrite
twisted\internet\tcp.py:248:doRead
twisted\internet\tcp.py:253:_dataReceived
twisted\protocols\tls.py:329:dataReceived
twisted\protocols\tls.py:295:_flushReceiveBIO
twisted\protocols\policies.py:110:dataReceived
autobahn\twisted\websocket.py:348:dataReceived
autobahn\websocket\protocol.py:1243:_dataReceived
autobahn\websocket\protocol.py:1255:consumeData
autobahn\websocket\protocol.py:1619:processData
autobahn\websocket\protocol.py:1747:onFrameEnd
autobahn\twisted\websocket.py:384:_onMessageEnd
autobahn\websocket\protocol.py:647:onMessageEnd
autobahn\twisted\websocket.py:387:_onMessage
binance\websocket\binance_client_protocol.py:31:onMessage
modules\order.py:373:listen_to_filled_orders
]. Retrying: 1

**Comment by andre9966** [comment]
If it can be useful, when I close the application I have this error:
![unhandled](https://user-images.githubusercontent.com/118386454/202307629-8480501c-21c2-4fe9-b97f-904fdb755513.PNG)

**Comment by escomputers** [comment]
Ok those DEBUG messages in green, confirm that application is working, input parameters have been validated correctly and Binance websocket connection has been started.
You have to click "Start" once, because connection to Binance was already set.
During working time if a BUY order is FILLED (100%), BASD will place your OCO order set previously (you dont'have to click anything). If order will be placed without errors you will see in the same window another green message with order details.

These errors you mentioned [here](https://github.com/escomputers/BASD/issues/45#issuecomment-1317755703) can be ignored since application was closed in unexpected way, I should just hide them.
